name: "Open Subtitles"
guid: "4b9ed42f-5185-48b5-9803-6ff2989014c4"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opensubtitles.png"
version: "18"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Download subtitles for your media"
description: "Download subtitles from the internet to use with your media files."
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.OpenSubtitles.dll"
changelog: |2-
  ### Bug Fixes ###
  - Fix pagination (#92) @MBR-0001

  ### Tests ###
  - Minor improvements (#90) @Bond-009

  ### Code or Repo Maintenance ###
  - Use meta ci (#101) @crobibero
  - chore(deps): bump Microsoft.NET.Test.Sdk from 16.11.0 to 17.0.0 (#91) @dependabot
  - Minor improvements (#90) @Bond-009
  - Replace %20 with + in SearchSubtitlesAsync (#89) @MBR-0001
  - Implement Bad Gateway handling & code cleanup (#87) @MBR-0001

  ### Dependency updates ###
  - chore(deps): bump Microsoft.NET.Test.Sdk from 16.11.0 to 17.0.0 (#91) @dependabot

  ### CI & build changes ###
  - Use meta ci (#101) @crobibero
