name: "Open Subtitles"
guid: "4b9ed42f-5185-48b5-9803-6ff2989014c4"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opensubtitles.png"
version: 19
targetAbi: "10.8.10.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Download subtitles for your media"
description: "Download subtitles from the internet to use with your media files."
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.OpenSubtitles.dll"
changelog: |2-
  ### New features and improvements ###
  - Add automatic invalidation of credentials (#128) @MBR-0001
  - Add handling for .strm files (#124) @MBR-0001

  ### Bug Fixes ###
  - Add automatic invalidation of credentials (#128) @MBR-0001

  ### CI & build changes ###
  - fix: meta ci workflows (#106) @h1dden-da3m0n
