name: "Open Subtitles"
guid: "4b9ed42f-5185-48b5-9803-6ff2989014c4"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opensubtitles.png"
version: "16"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Download subtitles for your media"
description: "Download subtitles from the internet to use with your media files."
category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.OpenSubtitles.dll"
  - "OpenSubtitlesHandler.dll"
changelog: |2-
  ### New features and improvements ###
  - Better download limit handling (#83) @MBR-0001
  - Implement default API key (#76) @MBR-0001

  ### Dependency updates ###
  - chore(deps): bump Microsoft.Extensions.Http from 5.0.0 to 6.0.0 (#79) @dependabot

  ### Code or Repo Maintenance ###
  - chore(deps): bump Microsoft.Extensions.Http from 5.0.0 to 6.0.0 (#79) @dependabot
