name: "Open Subtitles"
guid: "4b9ed42f-5185-48b5-9803-6ff2989014c4"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opensubtitles.png"
version: 23
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Download subtitles for your media"
description: "Download subtitles from the internet to use with your media files. (Requires configuration)"
category: "Subtitles"
artifacts:
  - "Jellyfin.Plugin.OpenSubtitles.dll"
changelog: |-
  - 5 requests per second, not 5 requests per 5 second (#175) @crobibero
  - Add bad subtitle handling (#165) @MBR-0001
